plugin:
  name: custom-data-type-iconclass
  version: 1
  url: https://github.com/programmfabrik/easydb-custom-data-type-iconclass
  displayname:
    de-DE: Iconclass-Verknüpfung
    en-US: Iconclass-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit dem Normdatendienst Iconclass her.
    en-US: Use for references to entities of Iconclass-AuthorityFile.
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-iconclass.js
    l10n: l10n/
    css: custom-data-type-iconclass.css
custom_types:
  iconclass:
    update:
      script: build/updater/iconclass-update.js
      timeout: 60
      batch_size: 50
      interval_base_config: update_interval_iconclass.days
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
      conceptAncestors:
        type: text
base_config:
  - name: update_interval_iconclass
    group: update_custom_data_type
    parameters:
      days:
        type: int
        min: 0
        default: 0
        position: 0
      default_language:
        type: text
        default: 'de'
        position: 1
